# Generated by Django 3.0.5 on 2020-05-15 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('user_id', models.CharField(max_length=25)),
                ('user', models.CharField(max_length=50)),
                ('is_retweet', models.BooleanField(default=False)),
                ('is_quote', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('quoted_text', models.TextField()),
            ],
        ),
    ]
