# Generated by Django 3.0.5 on 2020-05-30 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_detection', '0002_keyword_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to=settings.AUTH_USER_MODEL),
        ),
    ]
