# Generated by Django 3.0.5 on 2020-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_detection', '0004_auto_20200818_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
    ]
